targets:
  $default:
    builders:
      freezed:
        options:
          any_map: true
          explicit_to_json: true  
      embedded_config:
        options:
          app_config: 'lib/models/config/app_config.json'