name: spudly
description: A new Flutter project.

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: ^2.24.2
  # firebase_analytics: ^7.1.1 no nullsafe... skip it for now
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # google_sign_in:
  # apple_sign_in:
  get: ^4.1.3
  get_storage: ^2.0.2

  crypto: ^3.0.1
  http: ^1.1.2
  csv: ^5.0.0
  table_calendar: ^3.0.9
#dependency_overrides:
  # analyzer: 1.4.0
  # intl: 0.17.0

#dev_dependencies:

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
